name: Test code and publish package

on: [push]

jobs:
  deploy_linux:
    runs-on: ubuntu-latest
    container: quay.io/condaforge/linux-anvil-cuda:11.8

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v1

      - name: Build openmm package
        shell: bash -l {0}
        run: |
          git config --global --add safe.directory '*'
          conda install anaconda-client conda-build python=${{ matrix.python-version }}
          conda build recipe/ --output-folder ./pkg/ --no-include-recipe --no-anaconda-upload -c conda-forge

      - name: Upload to conda
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN_BASIC }} upload -u acellera pkg/linux-64/openmm-*.tar.bz2
